### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dee-y** [microrealestate/microrealestate#1]
Hi, i am a graphic designer and i love open source projects. If you would have me, i would create a logo for this project and it's free of course.

**Comment by camelaissani** [comment]
Hi, you're welcome to contribute to this project.
I'm looking forward to see your logo.

**Comment by camelaissani** [comment]
Better to work on [Loca](https://github.com/camelaissani/loca/issues/30) repository for this logo.
Thx
