### ISSUE TITLE
Any idea how I can make a deployment on a live server

### ISSUE THREAD

**Issue by softlockin** [microrealestate/microrealestate#100]
Would like to deploy the app on a cpanel server. Can you please help me on where to start ?

**Comment by camelaissani** [comment]
I'm sorry but I've never used cPanel.

However if you can get a Linux machine (Ubuntu) there, you might install `Docker` and `Docker compose`, pull the application source from github and start it.

When you will run the `mre` command, do not forget to set your domain if you have one or at least the machine IP to be able access the application.
By default the application is set to run on the localhost.
Also if you have a domain with a valid SSL certificate, you can replace `http` by `https`.

I hope it can help

**Comment by softlockin** [comment]
For the deployable version, I will try to separate the SERVICES and the WEBAPPS into differents NodeJS app that I will deploy isolately and try to synchronize them with the API.

**Comment by camelaissani** [comment]
> Thanks @camelaissani. Yeah it helps more than you know... Then, I'll try to deploy it on a Raspberry Pi while I am making deployable version.

I'd like to draw your attention to this issue #19
