### ISSUE TITLE
Docker-compose install

### ISSUE THREAD

**Issue by GregTroar** [microrealestate/microrealestate#101]
Hello,

Is there any guide to install with docker compose file ?
Tried all methods to install but no luck to get it work till now.

With mre I get to login / register screen, and once i click register nothing happens.
I can't register or login until I get an error at some point

**Comment by camelaissani** [comment]
What is the OS?
You might run the application in dev mode to have more logs.

**Comment by GregTroar** [comment]
Debian 11

**Comment by GregTroar** [comment]
tried several time with ./mre build and then ./mre start dev or ./mre start.
I cannot visit the page which for me is at http://10.10.10.8080/tenant
I try to register and it just tries for one minute then say: something went wrong.
Don't find anything in the logs.

Tried fresh install, removing the .env, nothing changes still the same.

**Comment by camelaissani** [comment]
It looks like the ip is not correct in the link you mentioned, no?

**Comment by GregTroar** [comment]
Yes typo error the local ip to access is http://10.10.10.21:8080/landlord
Anyway it works as I access the login page but from there I cannot create a new account. Indeed after entering the name / email / password and clicking OK I wait and I get a "something went wrong".
Anyway I stopped trying. Will try to find another alternative.

Thanks

**Comment by camelaissani** [comment]
OK then the UI might not access the backend services. What is the value of the `API_URL` in the `.env` file?
Do you have any logs in the browser console?

**Comment by GregTroar** [comment]
ok the API_URL was the issue, dunno why it was http://10.21/......
seems like a bug

**Comment by camelaissani** [comment]
Yep it's a bug. Here is the issue https://github.com/microrealestate/microrealestate/blob/master/cli/src/utils.js#L130 This code does not support the ip addresses :sob:

**Comment by GregTroar** [comment]
When using reverse proxy there is also a bug.
Cause it ends up adding the port number.
Anyway thanks I will test mre now.

**Comment by camelaissani** [comment]
Can you give me more details on the issue with the reverse proxy and the port number?

**Comment by GregTroar** [comment]
Sure it is just when you do a fresh install when it asks for the url i put https://mre.xxxx.com/landlord and in the env file it will create instead https://mre.xxxx.com:8080/landlord

Which would not work so I changed the .env file manually to remove the port it added.
