### ISSUE TITLE
Running Behind Nginx Proxy Manager 

### ISSUE THREAD

**Issue by upuldi** [microrealestate/microrealestate#107]
I am trying to run MRE on my Synology NAS behind the Nginx Proxy Manager. I modified the .env file as follows, built and started it. I also set up local DNS entries so I can access it locally without specifying a port in the DNS.

This is my .env file.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4620615/232272653-f22bf7dc-8a68-4f22-9d85-0643cac800e5.png">

This is my Nginx proxy manager setup.
![image](https://user-images.githubusercontent.com/4620615/232271051-6f361400-dad0-482d-a386-10d9af37e513.png)

I can access the site from the local DNS. 
![image](https://user-images.githubusercontent.com/4620615/232271237-c26268a5-e733-415b-bb52-c94e3cbdbd68.png)

However, with the above settings and the Nginx Proxy Manager settings, it appears that MRE cannot access the API, which leads to the following error.
![image](https://user-images.githubusercontent.com/4620615/232272774-3fd7ac1f-ceed-44a4-8d4f-ccb8763ad363.png)

What I am trying to achieve is running MRE behind Nginx so that I can access it easily without typing a URL path or ports. As I plan to run this on Synology, I want to use a different port. What is the best way to get this done?

**Comment by camelaissani** [comment]
It is weird. It looks like your config is good.
Did you check that all docker containers are up?
I just updated this diagram:
![](https://raw.githubusercontent.com/microrealestate/microrealestate/master/documentation/pictures/overview.png)
I hope it can help you to troubleshoot what is missing.

**Comment by mdy405** [comment]
Work fine for me behind Ngnix proxy manager, you have to specify the AUTHENTICATOR_URL in the .env file, so your Gateway can redirect the call to your authenticator service as the autenticator is not directly exposed on your host.
