### ISSUE TITLE
Build Error. 

### ISSUE THREAD

**Issue by Shubedobedo** [microrealestate/microrealestate#109]
Not sure if this is a bug in the code or my inexperience with docker. I can get it to work on a windows machine but not a linux vm.
Step 1: Create a new droplet on Digital ocean. Used the Docker Version 20.10.21OS Ubuntu 22.04
Step 2: Install Docker compose.
Step 3 :  sudo apt update
Step 4 : Git clone repo
Step 5 : cd microrealestate
Step 6 ./mre build
Step 7. I done a few different thing here think it was the issue maybe. I've done local host, IP and domain. All give same error
Then error :  
The command '/bin/sh -c yarn workspaces focus @microrealestate/tenant &&     yarn workspace @microrealestate/tenant run build' returned a non-zero code: 137
Service 'tenant-frontend' failed to build : Build failed
1

**Comment by camelaissani** [comment]
@Shubedobedo Most likely related to the machine size.
The build takes some memory and CPUs to deal with docker and the npm dependencies.

Thanks for your experimentation now we know the minimum size to use the app
