### ISSUE TITLE
Ability to Capture More Tenant Details - Feature Request

### ISSUE THREAD

**Issue by upuldi** [microrealestate/microrealestate#112]
It would be helpful to capture more details about the tenants, such as basic identification information like passport number, ID number, or driver's license number. Typically, I keep a copy of the identity document, so it would be better if we could also upload those documents.

**Comment by camelaissani** [comment]
The upload of documents is possible with the application. Currently there is an integration to use this provider https://www.backblaze.com/b2/sign-up.html which offers the First 10 GB for free.

You can configure it in the settings/third-parties page.

Once you set the backblaze keys, you will be able to define template documents that can be uploaded in settings/contracts.
![image](https://github.com/microrealestate/microrealestate/assets/7079471/b8d28ce3-96f8-458f-8697-e785538b061c)

After above configuration done, you will be able to upload documents for each tenant that uses the contract.
