### ISSUE TITLE
Tenant app phase 1

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#118]
Create an application for tenants where they can connect their account and access the following information:

- Name and address
- Lease details and the rented properties
- Scanned documents
- Last 12 invoices

![image](https://github.com/microrealestate/microrealestate/assets/7079471/6ff12c25-7317-441b-813d-cc7a6a1da603)

**Comment by camelaissani** [comment]
@vkanyoze not really started.
A preparatory phase need to be tackled on the mongo model and on the backend service before starting the tenant app.
I will detail this issue to have a complete description of what to achieve.

**Comment by mdy405** [comment]
@camelaissani I can help on this backend and/or frontend

**Comment by camelaissani** [comment]
Access to the scan documents will be implemented later
