### ISSUE TITLE
Unable to Create Accounts/Login (Something Went Wrong)

### ISSUE THREAD

**Issue by czanas** [microrealestate/microrealestate#119]
Hello, 

I have been interested in running this project but I am faced with an issue when trying to sign. I get the message "Something Went Wrong". Note that this is a fresh install.

I have tracked the issue a bit and it seems the `mongo` docker service is somehow not running. 

When performing the command `docker logs microrealestate-api-1 -f` I get the error 
`error: cannot connect to mongodb://127.0.0.1/mre` with more things. 

The command `./mre status` returns the following micro-services running:

```
microrealestate-api-1        
microrealestate-authenticator-1
microrealestate-emailer-1     
microrealestate-gateway-1
microrealestate-landlord-frontend-1 
microrealestate-pdfgenerator-1  
microrealestate-redis-1  
microrealestate-tenant-frontend-1  
```

Thanks

**Comment by ChipwizBen** [comment]
Same issue here, though my mongo is running. No errors appear in the docker logs.

Revisiting this project after 6 months. Seems that it's still plagued with basic setup issues. See you in another 6 months I guess.

**Comment by camelaissani** [comment]
@ChipwizBen see you in six months or maybe you can explain in more details how you setup the application to be able to unblock you. 

Usually this error happens when the `GATEWAY_URL` is not set properly. The frontend uses this environment variable to connect to the backend.
The domain set in this variable has to be accessible by the frontend.

Ofc any contributions are welcome.

**Comment by camelaissani** [comment]
Hello @czanas 

Indeed without mongo up and running no chance to have this application in good shape.

Did you try to only run mongo in a docker container to check what is wrong with it?

**Comment by czanas** [comment]
@camelaissani Yes I tried just running it by itself but it seems to stop running. 

I think it might be nice if you "undockerize" the project. I might try to do so myself.

**Comment by angyen** [comment]
Hi. I have just built the app in debian server and unable to create account. same problem of "Something went wrong"
and I tried to locate the .env file in the microrealestate folder but I can only find base.env file, edited the file and tweak the setting doesn't change the situation.
Am I getting the wrong .env file? I can't find other .env file besides this base.env
Please advice where goes wrong and how I should change to make it running.
