### ISSUE TITLE
FEATURE REQUEST: Add currency, Guatemalan Quetzal 

### ISSUE THREAD

**Issue by deivuh** [microrealestate/microrealestate#128]
Could Guatemalan Quetzal (Q or GTQ) me added to the list of supported currencies please? Or point me out where can I add new currencies to create a PR

**Comment by camelaissani** [comment]
It should be already provided by these two libs: https://github.com/microrealestate/microrealestate/blob/2e50e363dd85544ba44e1fd69eace700274c0b95/webapps/landlord/package.json#L42-L43

If not may be their versions have to be bumped up.

**Comment by deivuh** [comment]
Thanks @camelaissani, I just checked the repo of these packages and those are the latest versions available, and checked that Guatemalan Quetzal [is included](https://github.com/freeall/currency-codes/blob/6de7fe6c3cdbe094b917dad7de77af0d9141cae5/data.js#L570-L575) [on those](https://github.com/bengourley/currency-symbol-map/blob/01b9eb6236b902ec593751f13a18ef0f432dedb0/map.js#L66). 

However, it does not show up in the list when configuring the currency within microrealestate 

![image](https://github.com/microrealestate/microrealestate/assets/1679010/0311dcaa-1e6f-441d-845a-40229d49c810)

**Comment by deivuh** [comment]
My bad, just found it, it's under Quetzal (Q) 
![image](https://github.com/microrealestate/microrealestate/assets/1679010/f2b812b9-edc5-47be-bf95-127769112c76)

Thank you @camelaissani 

Closing this now
