### ISSUE TITLE
Unable to login to the new frontend

### ISSUE THREAD

**Issue by slmzayat** [microrealestate/microrealestate#13]
Hi,

I'm unable to sign in with the default account 'demo@demo.com:demo'.

I can't create a new username on http://localhost:8080/app/signup. I'm only getting 'Something went wrong' error.

I'm able to browse the deprecated Loca front-end just fine.

Please note this is the first time I'm using Docker. I'm using Windows and Build the application using the '$ ./mre.ps1 build'.

Is there any file I forgot to configure?

Thanks

**Comment by camelaissani** [comment]
Hi, 
Do you have any logs in the browser console?

**Comment by camelaissani** [comment]
Could you type this command in a terminal: `docker logs microrealestate_loca_1 -f` and try to login again and see if you get any errors in the terminal?

**Comment by slmzayat** [comment]
> Do you have any logs in the browser console?

I got the following errors:

1. TypeError: Cannot read property 'method' of undefined
2. TypeError: Cannot read property 'status' of undefined

Full log here: [sign in - browser console log.txt](https://github.com/microrealestate/microrealestate/files/6510431/sign.in.-.browser.console.log.txt)

> Could you type this command in a terminal: `docker logs microrealestate_loca_1 -f` and try to login again and see if you get any errors in the terminal?

Not seeing any error after I typed the [docker logs microrealestate_loca_1 -f.txt](https://github.com/microrealestate/microrealestate/files/6510425/docker.logs.microrealestate_loca_1.-f.txt)
command in powershell.

Thanks

**Comment by camelaissani** [comment]
Could you try the app in dev mode?  Run thi command '$ ./mre.ps1 dev'  and send me the log you get in the browser please.

**Comment by slmzayat** [comment]
Really appreciate your help. I've attached the log here 
[dev browser log.txt](https://github.com/microrealestate/microrealestate/files/6525845/dev.browser.log.txt).

Thanks

**Comment by camelaissani** [comment]
Thank you for using my project :wink: 

It looks like there is a problem in the authenticator service. Could you retest and send me the log from this command `docker logs microrealestate_authenticator_1 -f`?

**Comment by slmzayat** [comment]
PS C:\Users\slmzayat\Documents\GitHub\microrealestate> docker logs microrealestate_authenticator_1 -f
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
error:  message=ERR invalid password, stack=ReplyError: ERR invalid password
    at parseError (/usr/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/app/node_modules/redis-parser/lib/parser.js:302:14), command=AUTH, args=[change_this_password # TODO change this password], code=ERR
error: Forever detected script exited with code: 1

**Comment by camelaissani** [comment]
Ok I have an idea of what could be the root cause of the problem. It looks like the comments in the `prod.env` / `dev.env` files are not well handled.
Could you edit those files and remove the comments that are after the values? Like `# TODO change this password`, `# TODO change this secret` and `# TODO change this KEY`
For the demo, this should be enough to fix the problem :crossed_fingers: 

For production usage you should create a `.env` file where you will put your own secrets, keys, and password.

**Comment by slmzayat** [comment]
I'm sorry, it didn't work.

Should the passwords, keys, and secrets in the .env files follow a specific number format?

**Comment by camelaissani** [comment]
I'm gonna try to find a windows machine to check that.

**Comment by camelaissani** [comment]
@slmzayat could you fetch the latest update of the repository and check if the fix works on your side please?

**Comment by camelaissani** [comment]
@NightDog do you have a more elegant solution for this line https://github.com/microrealestate/microrealestate/blob/master/mre.ps1#L23 ?

**Comment by slmzayat** [comment]
> @slmzayat could you fetch the latest update of the repository and check if the fix works on your side please?

I'm afraid I can't test it now. Need to troubleshoot my docker.

Thanks again for your help. I hope your project goes well.
