### ISSUE TITLE
Build step failed

### ISSUE THREAD

**Issue by mdy405** [microrealestate/microrealestate#133]
those variables have to be set in .env file ? and when I put those variables in .env file and build again the API_URL is removed from the new generated .env file? Can you guys please clarify the build step. Thank you.

? Have you created a mailgun account for sending emails (https://www.mailgun.com/)? No
? Enter the URL to access the landlord front-end: http://localhost:8080/landlord
? Enter the URL to access the tenant front-end (it should share the same domain and port as the landlord front-end URL): http://localhost:8080/tenant
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"API_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LOGGER_LEVEL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"EMAILER_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"PDFGENERATOR_URL\" variable is not set. Defaulting to a blank string."      
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"API_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LANDLORD_FRONTEND_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"DOCKER_GATEWAY_URL\" variable is not set. Defaulting to a blank string."    
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"APP_NAME\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"SIGNUP\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LANDLORD_FRONTEND_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"REDIS_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"AUTHENTICATOR_PORT\" variable is not set. Defaulting to a blank string."    
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LOGGER_LEVEL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"REDIS_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"EMAILER_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"SIGNUP\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"AUTHENTICATOR_PORT\" variable is not set. Defaulting to a blank string."    
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"PDFGENERATOR_PORT\" variable is not set. Defaulting to a blank string."     
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LOGGER_LEVEL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"PDFGENERATOR_PORT\" variable is not set. Defaulting to a blank string."     
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"EMAILER_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LOGGER_LEVEL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"APP_NAME\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"PDFGENERATOR_URL\" variable is not set. Defaulting to a blank string."      
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"EMAILER_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"MONGO_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LOGGER_LEVEL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"GATEWAY_EXPOSE_FRONTENDS\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"AUTHENTICATOR_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"API_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"PDFGENERATOR_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"LANDLORD_FRONTEND_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"TENANT_FRONTEND_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"TENANT_FRONTEND_PORT\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"DOCKER_GATEWAY_URL\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"APP_NAME\" variable is not set. Defaulting to a blank string."
time="2023-10-17T21:46:16-04:00" level=warning msg="The \"TENANT_FRONTEND_PORT\" variable is not set. Defaulting to a blank string."
2023/10/17 21:57:38 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
2023/10/17 21:57:38 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
failed to solve: process "/bin/sh -c yarn workspaces focus @microrealestate/landlord &&     yarn workspace @microrealestate/landlord run build" did not complete successfully: exit code: 1
17

**Comment by mdy405** [comment]
@wuyonglong Well I'm on a Windows machine and still can't go through the build step

**Comment by wuyonglong** [comment]
@mdy405 I found my problem are different with you， my error is no @microrealestate/landlord which is @microrealestate/pdfgenerator,  now i solve the problem ,just change one dependencies version

**Comment by camelaissani** [comment]
@wuyonglong have you updated bcrypt?

**Comment by wuyonglong** [comment]
@camelaissani just puppeteer , I change to `"puppeteer": "19.11.1",`  then I  can build success
<img width="823" alt="image" src="https://github.com/microrealestate/microrealestate/assets/51282210/4f08d1ac-72c5-4fdd-a058-a25907d5d3cd">

**Comment by camelaissani** [comment]
@wuyonglong thanks for sharing. I'll update and test it asap

**Comment by wuyonglong** [comment]
@camelaissani You're welcome
