### ISSUE TITLE
Error: spawn docker-compose ENOENT

### ISSUE THREAD

**Issue by mgoerens** [microrealestate/microrealestate#135]
OS: Debian 12

```
  __  __   _                         ____                   _   _____         _             _          
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___ 
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|
                                                                                                       
The application designed to assist landlords in managing their properties and rentals

? Have you created a mailgun account for sending emails (https://www.mailgun.com/)? No
? Enter the URL to access the landlord front-end: http://localhost:8080/landlord
? Enter the URL to access the tenant front-end (it should share the same domain and port as the landlord front-end URL): http://localhost:8080/tenant
Error: spawn docker-compose ENOENT
-2
```

I've followed the official doc for installing `docker`

Reg. `docker-compose`, there is now a V2 that integrates it into the docker CLI. Hence all `docker-compose` commands should be transitioned to `docker compose` (remove hyphen). See https://docs.docker.com/compose/migrate/#what-does-this-mean-for-my-projects-that-use-compose-v1 for details.

I believe this is causing the issue above. I don't have a `docker-compose` command available on my system after following the official installation docs.

**Comment by camelaissani** [comment]
Thank you I'll check that asap

**Comment by mgoerens** [comment]
Testing now

**Comment by mgoerens** [comment]
Thanks for the quick fix !

Note that out of the box the ./mre script requires sudo (unless you configured your user to be allowed to use docker). It might be beneficial to implement a check that the current user is allowed to access the docker daemon and get an early exit to improve the user experience. I might take a stab at it if you're interested (no promise :) )

I ran into another issue, I'll open another one.
