### ISSUE TITLE
 How can I customize the lease template?

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#14]
Issue from Loca https://github.com/camelaissani/loca/issues/45

**Comment by camelaissani** [comment]
Few commits have been submitted so far:
https://github.com/microrealestate/frontend/commit/0fc8dad870bc2b44b0409be0e263c7a22809faad
https://github.com/camelaissani/loca/commit/a164ef638dfec56896f3b4bc36eade3f4bb7f177

The lease templates will be edited with [quilljs](https://quilljs.com/) editor. UI integration is [here](https://github.com/microrealestate/frontend/tree/master/src/components/RichTextEditor). The backend API involved is `/api/v2/templates` and code is [here](https://github.com/camelaissani/loca/blob/master/backend/routes/apiv2.js#L100-L106)

It is work in progress.

**Comment by pancodia** [comment]
@camelaissani Thanks a lot for the brilliant project. After a long while, I am revisiting this project and found a lot of progress. I am trying to create a custom template. I can draft a template using the quiljs editor and insert the provided placeholders. However, I couldn't find a way to generate a lease from a template for a tenant by replacing the the placeholders with his/her information. Is this part of the "work in progress"?

**Comment by camelaissani** [comment]
Yes it is :smile:

**Comment by camelaissani** [comment]
No true Mr Stale bot :slightly_smiling_face: I'm currently working on it.
I know I spend a lot of time on this but I guarantee I will resolve it.
