### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by RaiFernandesdosSantos** [microrealestate/microrealestate#143]
Tried building after setting up the .env file, but the build yet failed. It says the API_URL is not set, but the API_URL is in the .env file and after running the build it disappears

./mre build:

#0 building with "desktop-linux" instance using docker driver

#1 [pdfgenerator internal] load .dockerignore
#1 transferring context:
#1 transferring context: 94B done
#1 ...

#2 [pdfgenerator internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.24kB 0.0s done
#2 DONE 0.4s

#1 [pdfgenerator internal] load .dockerignore
#1 DONE 0.6s

#3 [pdfgenerator internal] load metadata for docker.io/library/node:18-alpine
#3 ERROR: error getting credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1/``

 > [pdfgenerator internal] load metadata for docker.io/library/node:18-alpine:

time="2023-11-18T23:21:28-04:00" level=warning msg="The \"API_URL\" variable is not set. Defaulting to a blank string."
failed to solve: node:18-alpine: error getting credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1/``
17

./mre start:

tenant-frontend Pulling 
 api Pulling 
 emailer Pulling 
 gateway Pulling 
 pdfgenerator Pulling 
 landlord-frontend Pulling 
 redis Pulling 
 mongo Pulling 
 authenticator Pulling 
error getting credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1/``
1

I tried downgrading the puppeteer to the 19.11.1 version, but it does not work

**Comment by camelaissani** [comment]
@RaiFernandesdosSantos have you recently cloned the repository?

**Comment by RaiFernandesdosSantos** [comment]
Yes, I even tried deleting and recloning

**Comment by camelaissani** [comment]
@RaiFernandesdosSantos Could you follow the installation procedure https://github.com/microrealestate/microrealestate#1-install-the-application and tell me if it fixed the issue?
