### ISSUE TITLE
Unable to find credentials 

### ISSUE THREAD

**Issue by narendra-bhole** [microrealestate/microrealestate#146]
I have created build and deployed mre. However it has not asked for any login details while setup and now I'm clueless what username and password to use for login for both Landlord and Tenant portal.

Does mre also has any administrative login apart from Landlord and Tenant logins

**Comment by narendra-bhole** [comment]
Reinstalled it and configured mailgun. New signup worked now.

**Comment by camelaissani** [comment]
Great that you find a solution to this issue.
Actually the Mailgun configuration should not have any side effect on the sign up.
By default the link to create an account should be visible in the login page like the screenshot below:

![Screenshot from 2023-11-28 23-24-13](https://github.com/microrealestate/microrealestate/assets/7079471/35a0ddf7-3320-4264-b3c9-7eed9876b7b4)
