### ISSUE TITLE
Latest commit [Jan 7, 2024] removed mre commans, how to run application in development mode now?

### ISSUE THREAD

**Issue by acrolink** [microrealestate/microrealestate#160]
I have used to run `./mre dev` to add translations and styling code to the application. Now in latest commit of Jan 7, 2024, the `mre` executive was removed. How to run the application in development mode now?

**Comment by camelaissani** [comment]
The [developer documentation](https://github.com/microrealestate/microrealestate/blob/master/documentation/DEVELOPER.md) has been updated.

Another option is to build the commands https://github.com/microrealestate/microrealestate/blob/master/cli/README.md

**Comment by acrolink** [comment]
So, I assume that, after I do some translation works, I can run `yarn prod` to build it for production?

**Comment by camelaissani** [comment]
Yes I also added these commands to build and to start the app in prod mode:
```
yarn run build
yarn start
```
