### ISSUE TITLE
Cannot see a form component to upload files [documents, PDF's etc..] to the cloud

### ISSUE THREAD

**Issue by acrolink** [microrealestate/microrealestate#163]
As can be seen, I see no way to a upload a file from my local computer.

![image](https://github.com/microrealestate/microrealestate/assets/13219117/d920bfa0-50bb-4c64-b394-c8c61844a63a)

**Comment by camelaissani** [comment]
Here you cannot upload documents if you have not define the upload templates in the contract form.
![Screenshot from 2024-01-27 19-27-07](https://github.com/microrealestate/microrealestate/assets/7079471/cad3dd63-ced2-4216-a771-2867bbae78a1)

I presumed that, for any given contract, we consistently prefer maintaining an unchanged list of documents.
