### ISSUE TITLE
Multiple expense items

### ISSUE THREAD

**Issue by narendra-bhole** [microrealestate/microrealestate#175]
Currently MRE supports only one expense items. It would be beneficial to enhance the system by providing the capability to add multiple expense items such as property tax, maintenance costs, and others specific to each property. Implementing this feature would greatly improve the functionality and usability of MRE. Your consideration in adding this feature would be highly appreciated.

**Comment by sebacampos** [comment]
+1. I would also like to track expenses. 

Might be duplicated: https://github.com/microrealestate/microrealestate/issues/99

**Comment by camelaissani** [comment]
@sebacampos yes it's a duplicate. I'll close it to keep #99
