### ISSUE TITLE
Error in downloading 

### ISSUE THREAD

**Issue by HusainSuksar** [microrealestate/microrealestate#177]
Cloning into 'microrealestate'...
remote: Enumerating objects: 7421, done.
remote: Counting objects: 100% (633/633), done.
remote: Compressing objects: 100% (419/419), done.
error: 3304 bytes of body are still expectedMiB | 1.27 MiB/s   
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by camelaissani** [comment]
@HusainSuksar this issue seems not be caused by the application it self.
I just googled the error and found this https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet
