### ISSUE TITLE
Translate the application in Brazilian

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#18]
Locale files:

- https://github.com/microrealestate/microrealestate/tree/master/webapps/landlord/locales
- https://github.com/microrealestate/microrealestate/tree/master/services/api/src/locales
- https://github.com/microrealestate/microrealestate/tree/master/services/emailer/src/emailparts/attachments/locale
- https://github.com/microrealestate/microrealestate/tree/master/services/emailer/src/emailparts/contents
- https://github.com/microrealestate/microrealestate/tree/master/services/pdfgenerator/templates/locales

Additional file:
- https://github.com/microrealestate/microrealestate/tree/master/webapps/tenant/locales/pt-BR.json
- https://github.com/microrealestate/microrealestate/tree/master/services/emailer/src/emailparts/contents/otp/pt-BR

**Comment by malacration** [comment]
I'm Brazilian, can I resolve this issue?

**Comment by camelaissani** [comment]
Yes of course you can. Your contributions are very welcome

**Comment by camelaissani** [comment]
@malacration some months ago you asked if you could translate the app in Brazilian.
For that purpose I listed the files/directories which have to be completed, see the issue description.
Also you can have a look at what have done @Markusi13 for the German in issue #51. 
The work to be done should be similar for Brazilian.

**Comment by emivaljr** [comment]
Hi @camelaissani. I am translating locally to Portuguese these files but the app is still in english. Everything locally is in pt_BR including my browser. Do I need to do something else?
