### ISSUE TITLE
Tenant login page is not responsive on mobile

### ISSUE THREAD

**Issue by MSoliven** [microrealestate/microrealestate#180]
<img width="319" alt="image" src="https://github.com/microrealestate/microrealestate/assets/8672584/aaaa962b-390b-416c-8b3c-719e8bf13f60">

As a workaround, I had to change the Card tag's **w-[32rem]** classname in Signin/page.tsx to "w-full".
Thanks.

**Comment by camelaissani** [comment]
Thanks @MSoliven Fixed!
