### ISSUE TITLE
getting "Can't open the page" error for the landlord signup page

### ISSUE THREAD

**Issue by hunkyn** [microrealestate/microrealestate#184]
Followed the installation instructions but when I go to http://192.168.30.9:9380/signup page it does not open. I looked into the container logs in portioner (Portainer is not managing this as I followed the instructions using ./mre start).  All containers were starting successfully except for the mongo one.

Here is the log from mongo container.

`t={"$date":"2024-06-02T20:47:36.261+00:00"} s=I c=WT id=22430 ctx=initandlisten msg=WiredTiger message attr={"message":{"ts_sec":1717361256,"ts_usec":261409,"thread":"1:0x7f1545a4fc80","session_name":"connection","category":"WT_VERB_BLOCK","category_id":3,"verbose_level":"NOTICE","verbose_level_id":-1,"msg":"unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.14"}}
t={"$date":"2024-06-02T20:47:36.261+00:00"} s=E c=WT id=22435 ctx=initandlisten msg=WiredTiger error message attr={"error":1,"message":{"ts_sec":1717361256,"ts_usec":261511,"thread":"1:0x7f1545a4fc80","session_name":"connection","category":"WT_VERB_DEFAULT","category_id":9,"verbose_level":"ERROR","verbose_level_id":-3,"msg":"__posix_open_file:815:/data/db/WiredTiger.wt: handle-open: open","error_str":"Operation not permitted","error_code":1}}
t={"$date":"2024-06-02T20:47:36.263+00:00"} s=W c=STORAGE id=22347 ctx=initandlisten msg=Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade.
t={"$date":"2024-06-02T20:47:36.263+00:00"} s=F c=STORAGE id=28595 ctx=initandlisten msg=Terminating. attr={"reason":"1: Operation not permitted"}
t={"$date":"2024-06-02T20:47:36.263+00:00"} s=F c=ASSERT id=23091 ctx=initandlisten msg=Fatal assertion attr={"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":676}
t={"$date":"2024-06-02T20:47:36.263+00:00"} s=F c=ASSERT id=23092 ctx=initandlisten msg=

***aborting after fassert() failure`

System: Ubuntu 22.04

I did search for this issue but could not find one similar.

**Comment by hunkyn** [comment]
Ok now i am getting the login page but getting the error when signing up.

**Comment by hunkyn** [comment]
Checking to see if anyone had any solution for this issue.

**Comment by camelaissani** [comment]
This might help: https://stackoverflow.com/questions/73152973/failed-to-start-up-wiredtiger-under-any-compatibility-version-this-may-be-due-t

**Comment by camelaissani** [comment]
I'll close this issue. Please reopen if needed.
