### ISSUE TITLE
Can't install microrealestate on Raspberry Pi 4

### ISSUE THREAD

**Issue by brunosalves** [microrealestate/microrealestate#19]
Hello there! I found about loca and microrealestate recently and I'm very interested in trying it to help me out organizing a coworking space a help managing, however, I'm facing a few problems while trying to build the app. I'm trying to run it on both Raspberry Pi 4 (2GB) and Raspberry Pi 4 (4GB) running raspbian buster and ubuntu. Notice: I'm not a developer, then some of the issues I'm facing might be noob issues, anyways, I really appreaciate any support you can give me.

First, I ran into a problem running the following command "apt install google-chrome-unstable" part in pdfgenerator/Dockerfile. I tried some workaround such as replacing it with "apt install google-chrome-stable" and I receive the same error message I decide to comment this command then the Dockerfile run completly with no error. I'm not sure though if there will be any upside because of this change, but it was the sollution I found so far. The original error log was the following:

"E: Unable to locate package google-chrome-unstable
The command '/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt-get update     && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont       --no-install-recommends     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'pdfgenerator' failed to build : Build failed"

Second, the installation proceeds to run loca/Dockerfile. Again, the installation crashes when trying to run "apt-get install -qqy mongodb-org-tools". I tried changing it to "apt-get install -qqy mongodb-org" and "apt-get install -y mongodb-org" but none of them work, so I just commented this mangodb-org installation and proceeded anyways. Probably this was not a good choice.

Third, the installation proceeds but crashes again with the following log message:

"> loca@0.1.0 buildprod /usr/app
> NODE_ENV=production node scripts/build.js

files built
npm ERR! code ENOTEMPTY
npm ERR! syscall rmdir
npm ERR! path node_modules/mozjpeg
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rmdir 'node_modules/mozjpeg'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-05T12_18_37_179Z-debug.log
The command '/bin/sh -c npm set progress=false &&     npm config set depth 0 &&     npm install forever -g --silent  &&     npm ci &&     npm run buildprod &&     NODE_ENV=production npm prune' returned a non-zero code: 217
ERROR: Service 'loca' failed to build : Build failed"

At this point I'm not sure if the errors I'm getting are a result of the modifications I made or if that's because of something else. Anyway, I hope someone can help me out. I'm looking foward to be able to run MRE on my local raspberry pi host and see what it can does.

**Comment by chedighribi** [comment]
Hi, i m facing the same issue did you find a solution ?

**Comment by brunosalves** [comment]
> 
> 
> Hi, i m facing the same issue did you find a solution ?

Hi, I gave up on MRE. I've been using Dolibarr instead and it is working perfectly so far.

**Comment by camelaissani** [comment]
@chedighribi unfortunately no. I'm looking for some help on this issue.

**Comment by karvounis** [comment]
@brunosalves How do you use Dolibarr to manage your real estate properties?

**Comment by camelaissani** [comment]
@karvounis I'll appreciate if you can ask your questions about Dolibarr in their repository. Thanks

**Comment by karvounis** [comment]
You are right! I am sorry about that. I will delete my comment asap

**Comment by camelaissani** [comment]
> You are right! I am sorry about that. I will delete my comment asap

Thanks 🙏

**Comment by camelaissani** [comment]
@chedighribi @brunosalves I made a fix on #81 which looks like similar of this issue. Could you make a try with the latest code please?
