### ISSUE TITLE
LocalStorage

### ISSUE THREAD

**Issue by wato1987** [microrealestate/microrealestate#194]
I'm having a bit of a brain melt and could use some help. I'm trying to figure out how to use local files instead of online storage (CDN) in this project.
Is there a way to configure the project to load resources from local storage rather than pulling them from a CDN? I've been staring at this for a while now and just can't seem to work it out.
Any pointers or guidance would be much appreciated. Thanks!

**Comment by rvz420** [comment]
Could you point where is using cdn's?

**Comment by camelaissani** [comment]
I'll close. Please reopen with more info.
