### ISSUE TITLE
razorpay payment gateway api support

### ISSUE THREAD

**Issue by test2a** [microrealestate/microrealestate#195]
https://razorpay.com/docs/api/

would it be possible to integrate razorpay as a payment gateway in the project?

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by test2a** [comment]
@brunoR1000 what is this?

**Comment by rvz420** [comment]
Currently, MRE doesn't expose an API, but here’s an idea for integrating payment gateways like Stripe, PayPal, and Mercado Pago. #117

**Comment by camelaissani** [comment]
I'll close. Please refer to #117
