### ISSUE TITLE
The system does not work when installing it from scratch

### ISSUE THREAD

**Issue by miguel2962** [microrealestate/microrealestate#198]
I gave up on the info from the old system I had installed but now I tried to install it from scratch and everything was installed without errors but it doesn't log in or create new users and it doesn't show any errors but I think it has to do with it not connecting to docker with the containers it creates when installing
![3](https://github.com/user-attachments/assets/1e85430c-0a74-4656-98d9-016b6a5e011d)

**Comment by UltimateStarCoder** [comment]
I am having the same issue as well!

**Comment by flowe14** [comment]
What was the resolution, I am having same issue.

**Comment by camelaissani** [comment]
Working on it #200

**Comment by UltimateStarCoder** [comment]
> Working on it #200

Thank you!
