### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by kevev** [microrealestate/microrealestate#20]
Great app! I am just now trying to get it running. There seems to be a CORS issue:

:8080/signup:1 Access to XMLHttpRequest at 'http://localhost:8080/api/v2/authenticator/signup' from origin 'http://167.71.22.26:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Any help is appreciated. :)

**Comment by kevev** [comment]
Resolved.

Change the APP_URL & API_URL the the IP address of your server as localhost won't work unless you are hosting locally:

vi .env

APP_URL=http://localhost:${APP_PORT}/${BASE_PATH}
API_URL=http://localhost:${NGINX_PORT}/api/v2

**Comment by camelaissani** [comment]
Have you set the `CORS_ENABLED` variable to `true` to be in such case?
