### ISSUE TITLE
REQ: Multiple occupencies for 1 property.

### ISSUE THREAD

**Issue by dgarner-cg** [microrealestate/microrealestate#202]
Good morning,

I currently manage a single property with multiple rental units, such as an apartment building, for example. I would like the ability to go into the property, select a multi-occupancy selection (Please add RV Park .. lol.) and then select how many units are available for rent and it will automatically add those N units as open.

Currently when I select Apartment and add a tenant, it shows 100% occupancy, even when adding "Surface: 50"

Thank you and have a blessed day.

**Comment by dgarner-cg** [comment]
I believe that would be a positive improvement if you decide to release a new major version. :p

**Comment by camelaissani** [comment]
I'll close this one similar to #10
