### ISSUE TITLE
What does Capital represent under Landlord Info in settings?

### ISSUE THREAD

**Issue by kevev** [microrealestate/microrealestate#21]
I am not sure what this field is for? It requires numerical value.

**Comment by camelaissani** [comment]
It means share capital. It is the amount invested by a company's shareholders for use in the business.
In several countries, you have to inject a minimum of money to be allowed to create a company.

Few examples
https://en.wikipedia.org/wiki/Public_limited_company#Share_capital

https://en.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_%C3%A0_responsabilit%C3%A9_limit%C3%A9e#Legal_characteristics

**Comment by kevev** [comment]
Thank You very much for explaining this to me. This app is great! Hoping to get it working for our specific use case.

**Comment by camelaissani** [comment]
I hope so too
