### ISSUE TITLE
Users get logged out when reloading page 

### ISSUE THREAD

**Issue by kevev** [microrealestate/microrealestate#22]
Reloading any page logs the user out.

**Comment by camelaissani** [comment]
Do you have any logs coming from the containers or/and from the browser console?

How do you run the app in dev mode or production mode?

**Comment by kevev** [comment]
I refreshed the page I was on: http://IPADDRESS:8080/Mission%20Open%20Air/rents/2021.06

Page shows: Cannot GET /Mission%20Open%20Air/rents/2021.06

Browser console shows: 2021.06:1 GET http://167.71.22.26:8080/Mission%20Open%20Air/rents/2021.06 404 (Not Found)

Running in productions mode on Ubuntu 20.04 VM.

**Comment by kevev** [comment]
Any help is appreciated.

Also wondering, do you provide paid development/support?

**Comment by camelaissani** [comment]
I'm on it.
Currently I'm not providing paid dev/support. I'm more looking for contributors.

**Comment by camelaissani** [comment]
I identified an issue when building the frontend docker container. The BASE_PATH variable was not taken in account.
Could you update your local repositories with the lastest commit and tell me if it fixes this issue?

**Comment by kevev** [comment]
Unfortunately I am not very good at programming javascript and web stuff. But I am great at testing and reporting issues.  :p

Thank You as this fixed the issue. I have another issue that I will post as new issue.
