### ISSUE TITLE
Refreshing browser page causes error

### ISSUE THREAD

**Issue by kevev** [microrealestate/microrealestate#26]
Refreshing on any page causes error.

Example on dashboard. Cannot GET /COMPANY%20NAME/dashboard

It seems as though the app is redirecting from /app to / .

Also, is it possible to have /app be default page as / is the old version?

**Comment by camelaissani** [comment]
I cannot reproduce. Could you give me more information about the steps to reproduce this issue? What is the error? Do you have any logs in the browser console or in the docker containers?

Weird that my last fix hasn't resolved this problem.

**Comment by kevev** [comment]
I did git pull. Would that not have pulled down the fix?

**Comment by camelaissani** [comment]
Could you remove everything and clone again may be something is wrong with your `prod.env` or `dev.env` files?
Could you add a `.env` file at the root of the directory (close to `prod.env` file) and put in there those lines:
```
DEMO_MODE=false
RESTORE_DB=false
```
I hope it will fix the issue.
