### ISSUE TITLE
 Unable to login to the new frontend

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#27]
Unable to login to the new frontend
It saying something wrong wrong, can you help me please?

**Comment by camelaissani** [comment]
Can you give me more details please?
Which OS ?
Are you running in production mode or in dev mode?
Do you have any crashes and call stacks in the browser console?
Do you have any logs in the docker containers?
Thanks

**Comment by adrianmartinezverax** [comment]
I’m running it in dev mode on Ubuntu 20.04 LTS.

But on windows machine running it locally is working all fine. So what is
do you think is the problem? Because I would really like to use it for
production and learning purposes.

**Comment by camelaissani** [comment]
Okay do you have any logs in the terminal where you've ran `mre dev` ?

**Comment by adrianmartinezverax** [comment]
here are the errors i am having below. and i am not in demo mode, when i am trying to create an account or login in it is always saying "something went wrong" and in loca it is saying " A technical issue has occurred (-_-')"

   TypeError: Cannot read property 'map' of undefined
    at /usr/app/backend/models/realm.js:97:25
    at Array.filter (<anonymous>)
    at /usr/app/node_modules/sugar/enumerable/internal/wrapNativeArrayMethod.js:12:21
    at Array.staticFn.instance (/usr/app/node_modules/sugar/common/internal/fixArgumentLength.js:10:12)
    at /usr/app/backend/models/realm.js:96:36
    at /usr/app/backend/models/model.js:39:7
    at /usr/app/backend/models/db.js:139:7
    at /usr/app/node_modules/mongojs/lib/cursor.js:73:24
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at runInAsyncScope (/usr/app/node_modules/mongojs/lib/cursor.js:195:16)
error: Forever detected script exited with code: 1
error: Script restart attempt #2
debug: loaded page accounting
debug: loaded page dashboard
debug: loaded page occupant
debug: loaded page owner
debug: loaded page print
debug: loaded page profile
debug: loaded page property
debug: loaded page realm
debug: loaded page rent
debug: loaded page signin
debug: loaded page signup
debug: loaded page website

**Comment by adrianmartinezverax** [comment]
sorry i was running ./mre build & ./mre start.  and here are the errors i
am having below. and i am not in demo mode, when i am trying to create an
account or login in it is always saying "something went wrong" and in loca
it is saying " A technical issue has occurred (-_-')"

   TypeError: Cannot read property 'map' of undefined
    at /usr/app/backend/models/realm.js:97:25
    at Array.filter (<anonymous>)
    at
/usr/app/node_modules/sugar/enumerable/internal/wrapNativeArrayMethod.js:12:21
    at Array.staticFn.instance
(/usr/app/node_modules/sugar/common/internal/fixArgumentLength.js:10:12)
    at /usr/app/backend/models/realm.js:96:36
    at /usr/app/backend/models/model.js:39:7
    at /usr/app/backend/models/db.js:139:7
    at /usr/app/node_modules/mongojs/lib/cursor.js:73:24
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at runInAsyncScope (/usr/app/node_modules/mongojs/lib/cursor.js:195:16)
error: Forever detected script exited with code: 1
error: Script restart attempt #2
debug: loaded page accounting
debug: loaded page dashboard
debug: loaded page occupant
debug: loaded page owner
debug: loaded page print
debug: loaded page profile
debug: loaded page property
debug: loaded page realm
debug: loaded page rent
debug: loaded page signin
debug: loaded page signup
debug: loaded page website

and here is my address for the microrealestate http://67.205.176.131:8080
 /     http://67.205.176.131:8080/app
