### ISSUE TITLE
Can you please include the code for Front-end please if possible? so i can put in .env i want to use it for production so i can use it to put my rents and some properties

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#29]
here is the only code i got for Loca, i am not sure if you really included Front-End

## loca
DEMO_MODE=false
RESTORE_DB=false
PRODUCTIVE=true
BASE_DB_URL=mongodb://mongo/locadb

## authenticator
AUTHENTICATOR_TOKEN_DB_PASSWORD=your_db_token_password
AUTHENTICATOR_ACCESS_TOKEN_SECRET=your_access_token_secret
AUTHENTICATOR_REFRESH_TOKEN_SECRET=your_refresh_token_secret

## emailer
MAILGUN_API_KEY=mailgun_api_key
MAILGUN_DOMAIN=mailgun_domain
EMAIL_FROM=billing-service@example.com
EMAIL_BCC=manager1@example.com,manager2@example.com
EMAIL_REPLY_TO=customer-service@example.com

**Comment by camelaissani** [comment]
Here are the environment variables you have to set for a productive application:

```
# Mongo
# TODO change this keys
CIPHER_KEY=change_this_cipher_key
CIPHER_IV_KEY=change_this_cipher_iv_key

## authenticator
# TODO change this password
AUTHENTICATOR_TOKEN_DB_PASSWORD=change_this_password
# TODO change these secrets
AUTHENTICATOR_ACCESS_TOKEN_SECRET=change_this_access_token_secret
AUTHENTICATOR_REFRESH_TOKEN_SECRET=change_this_refresh_token_secret
AUTHENTICATOR_RESET_TOKEN_SECRET=change_this_reset_token_secret

## emailer
# TODO change this keys
MAILGUN_API_KEY=your_api_key
MAILGUN_DOMAIN=mg.example.com
EMAIL_FROM="Example <noreply@example.com>"
EMAIL_REPLY_TO=customer-service@example.com
EMAIL_BCC=manager1@example.com,manager2@example.com

## api
DEMO_MODE=false
RESTORE_DB=false
```

The keys and tokens can be randomly generated with JS code in the terminal by running the node console:

```
$ node
> require('crypto').randomBytes(64).toString('hex')
```

For the emailer section, you will have to create an account here https://signup.mailgun.com/new/signup

**Comment by adrianmartinezverax** [comment]
Thank you so much, I really appreciate!
