### ISSUE TITLE
./mre dev issues

### ISSUE THREAD

**Issue by qjay** [microrealestate/microrealestate#30]
after running /mre dev succesfully got issues with localhost/app see feedback
![image](https://user-images.githubusercontent.com/13147840/129341706-7e16cecd-bd2c-425c-b38d-1b53c7c5b501.png)
and cannot go beyond here am still new to docker technology

**Comment by qjay** [comment]
docker status

![Screenshot from 2021-08-13 13-13-42](https://user-images.githubusercontent.com/13147840/129342475-f3cd81d9-785e-4ce2-8da9-bbf01cfa3327.png)

**Comment by camelaissani** [comment]
I think here you are mixing the prod and dev modes.
Your snapshot shows the logs from the prod mode.

**Comment by camelaissani** [comment]
@qjay do you still have this issue on your side?
