### ISSUE TITLE
What are server requirements?

### ISSUE THREAD

**Issue by ugintl** [microrealestate/microrealestate#31]
Can it run on Apache, php, mysql hosting?

**Comment by camelaissani** [comment]
Personaly I run the services of this app on a basic Digital Ocean droplet (a cloud VM): 
Memory: 1GB 
CPU: 1 
SSD: 25 GB
transfert: 1000GB

The UI runs on Vercel.

No need of Apache, php and mysql. 
The app is fully written in JS and the services use the nodejs runtime and run inside docker containers.
The web server used is NGINX and the databases are: MongoDB and Redis. All these provided through docker containers.
