### ISSUE TITLE
mongo db as separate container

### ISSUE THREAD

**Issue by ysnoussi** [microrealestate/microrealestate#4]
Would be good to run mongo on its own container

**Comment by camelaissani** [comment]
Actually, mongo runs in its own container https://github.com/microrealestate/microrealestate/blob/master/docker-compose.microservices.base.yml

I guess you would like to not use the one from the compose wouldn't you?

**Comment by ysnoussi** [comment]
My bad, I read loca Dockerfile too fast. 
I would like to thank you for this project. Let me know if I can help.
