### ISSUE TITLE
502 issue while creating first organisation

### ISSUE THREAD

**Issue by saikiruba-mj** [microrealestate/microrealestate#44]
Hi

@camelaissani 

I have checked the microrealestate application in the dev (./mre dev) modes with .env file filled with the latest config and repository changes(https://github.com/microrealestate/microrealestate/commit/c664a7d334d4b07ae92e4e6ab4edfea5f1422cee). While login as first access we unable to create organisation(**502 issue**)

**Browser Screenshot:**

![image](https://user-images.githubusercontent.com/74354881/144213061-3920d8e6-37c8-48fa-abf6-00f1b18136c6.png)

**Terminal Screenshot:**

![image](https://user-images.githubusercontent.com/74354881/144213621-fa75d216-bc41-4bb4-8c43-bdb6e9eccb41.png)

Kindly let us know there is any solution to fix this issue.

Thank you!

**Comment by camelaissani** [comment]
Hi @saikiruba-mj my last commit should fix the problem.

**Comment by saikiruba-mj** [comment]
Hi @camelaissani 

Its working fine from my end with latest commit(504413a)

Thank You!
