### ISSUE TITLE
Error while fetching email data return 422 error code

### ISSUE THREAD

**Issue by saikiruba-mj** [microrealestate/microrealestate#45]
Hi!

@camelaissani

I have checked the microrealestate application in the dev (./mre dev) modes with .env file filled with the latest config and repository changes(2602771). While sending an invoice or rentcall mail from the Rents tab we are facing issues like "Request failed with status code 422"

Terminal Screenshot:

![image](https://user-images.githubusercontent.com/74354881/145004586-1aa92f48-d3b5-495b-b0c2-090010f8e515.png)

**Note**:  I have just added logger to debug the issue no code changes are done with latest commit(2602771)

It seems like the issue in the following file https://github.com/microrealestate/microrealestate/blob/master/services/emailer/src/emaildata.js, there are no data directory in mentioned directory path code on latest changes.

Kindly let us know there is any solution to fix this issue.

Thank you!

**Comment by camelaissani** [comment]
@saikiruba-mj fixed!

**Comment by saikiruba-mj** [comment]
@camelaissani 

Now I am facing an issue while sending reset password mail.

Emailer works fine for rent call, rentcall_reminder, rentcall_last_reminder,  and invoice flow.

**Terminal screenshot:**

![Screenshot from 2021-12-14 16-38-57](https://user-images.githubusercontent.com/74354881/145987394-5200efe4-65d9-4d4a-877a-75c99fd92b4e.png)
