### ISSUE TITLE
Having some errors with the new version

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#46]
No stopped containers
Service 'pdfgenerator' failed to build : The command '/bin/sh -c yarn global add forever &&     yarn workspace pdfgenerator install --production &&     yarn cache clean' returned a non-zero code: 1
1

**Comment by camelaissani** [comment]
@adrianmartinezverax I cloned the app on my side and followed the README instructions and everything was working fine on Ubuntu.

Which OS are you using?
I need more details on how you start the app.

**Comment by adrianmartinezverax** [comment]
I cloned the app too.

I am using Ubuntu 20.04 LTS

I started the app following all the instructions in README

**Comment by camelaissani** [comment]
Ok. Is it working if you start the application in dev mode?
`./mre dev`

**Comment by adrianmartinezverax** [comment]
yes it is, only in the production not working

**Comment by hasheemm1** [comment]
> yes it is, only in the production not working

sometimes there is a network timeout issue and it manifests itself in a retry loop until it just gives up. add a large timeout  to the yarn workspace command in the Dockerfile of all the microservices

--network-timeout 1000000

**Comment by camelaissani** [comment]
Is is still the case with the last commits?

**Comment by adrianmartinezverax** [comment]
no everything works fine. thank you
