### ISSUE TITLE
Document deployment on AWS

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#47]
Document the steps to follow to deploy MRE services and front-end on AWS

**Comment by camelaissani** [comment]
@hasheemm1 I saw you did a great job on your fork and you achieved to deploy this project on AWS.
Would you mind to contribute to this repository by writting the procedure you followed to have the app on AWS?

**Comment by hasheemm1** [comment]
YesI will do, My apologies for not reaching out sooner, I have meant to. 

My fork demonstrates a GitHub actions CI pipeline to AWS ECS, using the great work done by the Docker Compose team in partnership with AWS Fargate.

My prod version on ECS Fargate is 5 days stable and works well. CF Creates, Updates, and Deletes work perfectly. 

Outstanding issues:

1. mre CLI li needs a change to request db and email tokens from github secrets (currently I've checked in my .env file)
2. CF updates sometimes changes container IP's and the reverse proxy can't resolve the containers. Nginx DNS resolver cache must be cleared on every build (I need to automate this), That being said, with the power of AWS ALB there is probably no need for nginx reverse proxy.. that's a future battle.

Thank you for a great repo.
