### ISSUE TITLE
Having some errors with the new version on my machine.: zsh: exec format error: ./mre

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#48]
➜  ~ cd desktop
➜  desktop cd microrealestate 
➜  microrealestate git:(master) ./mre build
zsh: exec format error: ./mre
➜  microrealestate git:(master)

**Comment by adrianmartinezverax** [comment]
Yes I am on Mac

**Comment by camelaissani** [comment]
@hasheemm1 thanks for your help I appreciate :+1: 

@adrianmartinezverax have you solved your problem by using the `mre-macos` command?

You just have to run: `./mre-macos build`

**Comment by adrianmartinezverax** [comment]
Thank you so much, it works fine 👍
