### ISSUE TITLE
E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by ortizman** [microrealestate/microrealestate#5]
Hi,
I get the following error when I try to build the project
`./mre build`

`E: Unable to correct problems, you have held broken packages.`

Apparently it's time to build the image docker of **loca**, try to install the packete mongodb-org-tools, and this breaks because it can not solve a dependency

`mongodb-org-tools : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable`

**Comment by ortizman** [comment]
Ok, this happens because the docker image of node:8 changed its base from debian jessie to stretch.
I created a PR with the changes
https://github.com/camelaissani/loca/pull/38

**Comment by camelaissani** [comment]
Great!
Is it related to this issue https://github.com/nodejs/docker-node/issues/1012 from Docker?
