### ISSUE TITLE
register first user error

### ISSUE THREAD

**Issue by mkoetzing** [microrealestate/microrealestate#58]
hi folks,
i configured microrealestate to use without mailgun. when trying to add the first and initial user I always get an error. do i miss something? 
thanks for your work and regards,
martin

**Comment by mkoetzing** [comment]
when trying to run in debug mode this happens:

```
warning " > eslint-config-next@12.0.3" has unmet peer dependency "next@>=10.2.0".

warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

```

**Comment by camelaissani** [comment]
Can you tell me what is the error in the browser console?
Which OS are you using? Do you run the app on your local machine?

**Comment by mkoetzing** [comment]
![image](https://user-images.githubusercontent.com/19590502/155137673-5d944599-9655-4d15-91c1-9a9fbd07a33f.png)

**Comment by mkoetzing** [comment]
![image](https://user-images.githubusercontent.com/19590502/155139715-2632188d-3391-47e8-8390-a4201b432234.png)

this happens when starting in normal mode and trying to register...any chance to find more log-details?

**Comment by mkoetzing** [comment]
![image](https://user-images.githubusercontent.com/19590502/155157991-60513cd9-bd0d-40db-b177-db2d28d5ad23.png)

**Comment by camelaissani** [comment]
I see what can be the problem.
Most likely you have not entered the right URL when `mre` command prompt this:
![image](https://user-images.githubusercontent.com/7079471/155199414-ec30eba8-3edc-4c41-a348-3e6c39a8715a.png)
You probably kept the default value which is good if you do a local installation.

In your case you should have set something like `http://[here the IP address of your ubuntu machine]:8080/app` ie `http://68.1.2.3.4:8080/app`.

If you have a domain which points to your machine and valid SSL certificate you can also set the URL as the following: 
`https://[your domain]/app` ie `https://www.example.com/app`

Two options to reset this:
1. remove the `.env` file and rerun the `mre` command  /!\ with this option you loose all the data previoulsy stored in the app 
2. edit the `.env` file and replace the `http` and `localhost` by the expected values from these lines:
```
APP_URL=http://localhost:${NGINX_PORT}${BASE_PATH}
API_URL=http://localhost:${NGINX_PORT}/api/v2
```

Do not forget to restart the app after the modifications.

**Comment by mkoetzing** [comment]
thanks i will try. i thought it defaults to the given ip.

**Comment by mkoetzing** [comment]
thank you for the help. it was indeed the wrong adress (localhost instead of remote-host-address). all the best
