### ISSUE TITLE
How to build on windows ???

### ISSUE THREAD

**Issue by raphitit** [microrealestate/microrealestate#6]
Hello, I'm not too comfortable with the command lines, and I tried to follow your explanation but I did not understand too much because every time I get an error, either on PowerShell or subsystem linux. I am French and I would like to have help to build it and start it. Otherwise great work.
_

**Comment by camelaissani** [comment]
Hello well I've never checked my script on Windows. It surely needs some enhancements to run on this OS.
I'll be happy if you could help me to make it running on Windows.
BTW I'm French too :)

**Comment by raphitit** [comment]
Je serai heureux de vous aider, mais je suis vraiment amateur et je peu vous aider un peu

**Comment by camelaissani** [comment]
I keep writing in english. This issue could be useful for others.

I see two ways for fixing this issue for Windows users:
- Port the `mre` bash file to MS-DOS or PowerShell script
- Publish the images built by `mre` in docker hub or something equivalent each time there is a new release of microrealestate

Obviously, we could implement the two solutions. The second option will avoid to build images and facilitate a bit the first usage of the application.

**Comment by camelaissani** [comment]
Issue should be fixed by #9 
Thank you @NightDog for your contribution
