### ISSUE TITLE
Looks like a bug on Enter Rent Settlement Button, Its literally doing nothing.

### ISSUE THREAD

**Issue by adrianmartinezverax** [microrealestate/microrealestate#61]
<img width="1788" alt="Screen Shot 2022-02-23 at 11 43 25 AM" src="https://user-images.githubusercontent.com/45777622/155295038-fc0342f0-fccc-446a-a278-cd6211ccf734.png">

**Comment by camelaissani** [comment]
Enter a rent with no tenants is not possible

**Comment by camelaissani** [comment]
Regarding my last comment, do you see something to do here?

**Comment by adrianmartinezverax** [comment]
Awesome I added my own clients and it works, but on demo data not working.
