### ISSUE TITLE
locale seems not to affect calendar

### ISSUE THREAD

**Issue by loewensteinph** [microrealestate/microrealestate#63]
Locale is DE wheras the dashbord shows PT month name, same applies to datepicker calendar 

![grafik](https://user-images.githubusercontent.com/17300968/155370106-3419ae01-26b5-496a-8e62-6390b19ac956.png)

![grafik](https://user-images.githubusercontent.com/17300968/155370439-288d2acd-a71e-4376-8e6e-ddd93b6f089d.png)

**Comment by camelaissani** [comment]
@loewensteinph  It should be fixed now
