### ISSUE TITLE
Contract breakdown

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#69]
Contract breakdown
E.g
Yearly rental may be 20000.00
Breakdown:
Initial payment in cash : 3000.00
Balance paid in post dated cheques
Options:
1 Cheque
2 Cheques
4 Cheques
5 Cheques

**Comment by camelaissani** [comment]
@pmzhou have you considered to create a contract with paiement per month even if it is a yearly rental?
Like that you will be able to enter the different post dated payments at the right time frame.
wdyt?

**Comment by pmzhou** [comment]
I tried it. Since it's a post dated cheque, there could be a reminder on the day which the user responds to by affirming the cheque went through and if it didn't, you have to put a note for a penalty or some other condition

**Comment by camelaissani** [comment]
I don't know if you saw that, but you can add additional fees for each payment:

![image](https://user-images.githubusercontent.com/7079471/155775304-8988283a-fb20-4b19-b954-7cd349e6ec71.png)

Is this can work for you?

**Comment by pmzhou** [comment]
Maybe I have to reset all data start on a clean slate for me to see these settings
How do you reset Demo data?
________________________________

**Comment by camelaissani** [comment]
Actually, even in demo mode you can see the feature I described above.
Go to the rents page and select a rent to pay. The payment page will be shown. There you will be able to see different tabs.
The second tab is the one where you can add additional fees and discounts.

You can remove the demo data by deleting the `.env`  file at the root of the project, and restart the application by running the `mre start` command.
At the prompt choose the `empty data` option.
Be aware that you will loose all your previous data entered in the app.
