### ISSUE TITLE
/bin/sh: 1: wget: not found E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

### ISSUE THREAD

**Issue by silicon755** [microrealestate/microrealestate#7]
I am running the app on Linux Kali Rolling and execution of `./mre build` I get the following error
`/bin/sh: 1: wget: not found
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
ERROR: Service 'pdfgenerator' failed to build: The command '/bin/sh -c wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'     && apt-get update     && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont       --no-install-recommends     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 255
`

**Comment by camelaissani** [comment]
I just reproduced the issue. I work on it.

**Comment by camelaissani** [comment]
Should be fixed now
