### ISSUE TITLE
Add UAE currency (AED)

### ISSUE THREAD

**Issue by camelaissani** [microrealestate/microrealestate#72]
Add UAE currency (AED)

**Comment by camelaissani** [comment]
@pmzhou it looks like it's already supported.

You can change the currency in `Settings/landlord form` and pick AED from the currency dropdown:

![image](https://user-images.githubusercontent.com/7079471/155780572-75b9b632-7d5d-409e-87fd-54f37087aab6.png)

**Comment by pmzhou** [comment]
My bad for this one. Found it. Thanks

________________________________
