### ISSUE TITLE
Can not create an account

### ISSUE THREAD

**Issue by pmzhou** [microrealestate/microrealestate#77]
![Screenshot_select-area_20220401115541](https://user-images.githubusercontent.com/10725833/161220697-2f0d61ad-f13b-4a63-af2a-e328902b990a.png)

Can not create a new user on a new installation.
Error : Something went wrong

**Comment by camelaissani** [comment]
It looks like you haven't configured correctly the app.
When you ran the `mre` command, you might miss to set the url to access the app. I'm referring this prompt "Enter the URL to use to access the front-end"

Probably you installed the app on a machine from digital ocean, aws...
In this case you should pass the url like that `http://x.x.x.x.x/app` Where `x.x.x.x.x` is the IP address of your machine

In case you have a dedicated domain, you can replace the IP by the domain.
If you have SSL certificate, you can replace `http:` by `https:`

Here are the variants:
```
http://x.x.x.x.x/app
http://mydomain/app
https://mydomain/app
```
