### ISSUE TITLE
Rent amounts don't calculate correctly

### ISSUE THREAD

**Issue by paradixe** [microrealestate/microrealestate#78]
![image](https://user-images.githubusercontent.com/10002681/167010426-b43107d6-6b0c-485b-9c38-d77101438123.png)
Am I doing something wrong?

![image](https://user-images.githubusercontent.com/10002681/167010585-32036893-8965-45db-bb7c-8b2002e98c34.png)

Any help would be appreciated. Installed on Windows 11 + Docker Desktop

**Comment by camelaissani** [comment]
From your screenshots, I would say that the expenses were concatenated with the rent amount.
Could you check that you have no spaces in the expense field from the tenant contract?
You might not use a comma but a point in numbers.

**Comment by camelaissani** [comment]
Also your amounts should not start with a zero. You should not have `0700` but `700`

**Comment by camelaissani** [comment]
I just fixed the issue. Pull the repo and edit and save the tenant form should fix the problem.
