### ISSUE TITLE
Installing gives demo page

### ISSUE THREAD

**Issue by AndriyMulyar** [microrealestate/microrealestate#8]
Hi,

Great work with this project. Is there an easy way to automatically clean all the database entries / alter some global config to customize for your needs? I was able to get the orchestrated containers all working but it only brings up the demo version with pre-loaded information.

Thanks!

**Comment by camelaissani** [comment]
Hi sorry for my late answer.

Actually, the application was not fully ready to be used without pre-loaded data.
Now it's possible (please pull the last version of the project). 
You just have to create a `.env` file at the root of the project with the following content:
```
## loca
DEMO_MODE=false
RESTORE_DB=false
PRODUCTIVE=true
BASE_DB_URL=mongodb://mongo/locadb

## authenticator
AUTHENTICATOR_TOKEN_DB_PASSWORD=your_db_token_password
AUTHENTICATOR_ACCESS_TOKEN_SECRET=your_access_token_secret
AUTHENTICATOR_REFRESH_TOKEN_SECRET=your_refresh_token_secret

## emailer
MAILGUN_API_KEY=mailgun_api_key
MAILGUN_DOMAIN=mailgun_domain
EMAIL_FROM=billing-service@example.com
EMAIL_BCC=manager1@example.com,manager2@example.com
EMAIL_REPLY_TO=customer-service@example.com
```
You can name your database as you want, here I put `locadb`
Also, I recommand you to change the password and the secrets.
For sending emails to the tenants, you will have to subscribe to the [mailgun](https://www.mailgun.com/) service and update the emailer section with your email addresses.

**Comment by AndriyMulyar** [comment]
Thank you for the update!
