### ISSUE TITLE
Fresh Install -  What is the correct process to perform a fresh install of this image.

### ISSUE THREAD

**Issue by jeff0540** [microrealestate/microrealestate#84]
This is what I am getting when attempting to re-insstall.

The application which helps the landlords to manage their property rents

? Have you created a mailgun account for sending emails (https://www.mailgun.com/)? No
? Enter the URL to access the landlord front-end: http:/10.0.0.166:8080/landlord
? Enter the URL to access the tenant front-end (it should share the same domain and port as the landlord
front-end URL): http://10.0.0.166:8080/tenant
No stopped containers
Build or rebuild services.

Services are built once and then tagged as `project_service`,
e.g. `composetest_db`. If you change a service's `Dockerfile` or the
contents of its build directory, you can run `docker-compose build` to rebuild it.

Usage: build [options] [--build-arg key=val...] [SERVICE...]

Options:
    --compress              Compress the build context using gzip.
    --force-rm              Always remove intermediate containers.
    --no-cache              Do not use cache when building the image.
    --pull                  Always attempt to pull a newer version of the image.
    -m, --memory MEM        Sets memory limit for the build container.
    --build-arg key=val     Set build-time variables for services.

Any assistance would be greatly appreciated.

**Comment by camelaissani** [comment]
You mentioned reinstall, I assume you already installed it before. In this case you might run the `mre stop` command and remove the `.env` file to clean the previous installation.

In a second step you will be able to build and start a fresh installed app.
