### ISSUE TITLE
yarn install network timeout needs to be set higher

### ISSUE THREAD

**Issue by k----n** [microrealestate/microrealestate#85]
It seems like when the container images are building, they are fighting for bandwidth so it becomes really slow to fetch packages with yarn.

I had to add `--network-timeout 600000` (10 minute timeout) to `yarn install` for each of the Dockerfiles to prevent connection errors.

**Comment by robbinmoreka** [comment]
how do i add this please

**Comment by robbinmoreka** [comment]
> how do i add this please

already in the root of ubuntu desktop:~/microrealestate 

I can't fully install the program please help

**Comment by robbinmoreka** [comment]
> > how do i add this please
> 
> already in the root of ubuntu desktop:~/microrealestate
> 
> I can't fully install the program please help

docker and containers running well
