### ISSUE TITLE
CLI does not restore backup

### ISSUE THREAD

**Issue by k----n** [microrealestate/microrealestate#86]
I had to manually connect to the Docker container to restore

```
docker exec -it microrealestate_mongo_1 bash
mongorestore --gzip --archive=backup/demodb.dump
```

**Comment by camelaissani** [comment]
Do you have any logs to understand what is not working properly please?

**Comment by k----n** [comment]
When I ran:
```sh
./mre restoredb
```

It says that the restore was successful, but when I actually looked at the mongo database it was empty.
Hence, why I manually connected to the Docker container and ran the `mongorestore` command.

**Comment by camelaissani** [comment]
Did you get prompted to select the dump file?

Also the exe needs to run with .env file corrected set.
Is the BASE_DB_URL env was with the correct connection string to connect to the database to restore?

**Comment by k----n** [comment]
Yes there was a prompt.

I already deleted the instance that was running microrealestate, but if i recall correctly, BASE_DB_URL was probably `mongodb://mongo/demodb`.

BASE_DB_URL was never changed from the default.

**Comment by camelaissani** [comment]
@k----n I think I reproduced the issue. Usually I restore the DB while the application is running. This way it works. 
I guess you tried to restore with the application not started. In this case the CLI does not work.
