### ISSUE TITLE
Can I use just docker compose?

### ISSUE THREAD

**Issue by samcov** [microrealestate/microrealestate#89]
There doesn't appear to be any attempt to just show how to use the yml files with docker compose.

Is it as simple as just changing the urls, and either using or not using the emailing system?

**Comment by camelaissani** [comment]
Thoriticaly replacing the env variables in the yml files should do the trick.

In this file you can find which yml have to be used to run the app  https://github.com/microrealestate/microrealestate/blob/master/cli/src/utils.js#L97

**Comment by samcov** [comment]
Thanks, I'll take a look!

**Comment by samcov** [comment]
Wait, looking at this, it looks like what the mre.exe would do.

So is the mre just a node app converted into an executable?

The only reason I'm asking for the docker compose, is because I would deploy this on Linux.

**But if I can run your mre app on linux, then problem solved**.

**Comment by camelaissani** [comment]
Yes it's a node app converted in an executable for Windows, Mac and linux.
