### ISSUE TITLE
Noob that cant fully install the program

### ISSUE THREAD

**Issue by robbinmoreka** [microrealestate/microrealestate#91]
the install can't go past this point please help
 |  \/  | (_)   ___   _ __    ___   |  _ \    ___    __ _  | | | ____|  ___  | |_    __ _  | |_    ___
 | |\/| | | |  / __| | '__|  / _ \  | |_) |  / _ \  / _` | | | |  _|   / __| | __|  / _` | | __|  / _ \
 | |  | | | | | (__  | |    | (_) | |  _ <  |  __/ | (_| | | | | |___  \__ \ | |_  | (_| | | |_  |  __/
 |_|  |_| |_|  \___| |_|     \___/  |_| \_\  \___|  \__,_| |_| |_____| |___/  \__|  \__,_|  \__|  \___|

The application which helps the landlords to manage their property rents

Found .env file and rely on it to run

tenant-frontend Pulling
landlord-frontend Pulling
tenant-frontend Warning
landlord-frontend Warning
#1 [mre/landlord-frontend:latest internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.01kB 0.0s done
#1 DONE 0.0s

#2 [mre/tenant-frontend:latest internal] load .dockerignore
#2 transferring context: 32B
#2 transferring context: 34B done
#2 DONE 0.1s

#3 [mre/tenant-frontend:latest internal] load build definition from Dockerfile
#3 transferring dockerfile: 972B done
#3 DONE 0.1s

#4 [mre/landlord-frontend:latest internal] load .dockerignore
#4 transferring context: 34B done
#4 DONE 0.1s

#5 [mre/tenant-frontend:latest internal] load metadata for docker.io/library/node:16-alpine
#5 ...

#6 [auth] library/node:pull token for registry-1.docker.io
#6 DONE 0.0s

#5 [mre/tenant-frontend:latest internal] load metadata for docker.io/library/node:16-alpine
#5 DONE 5.0s

#7 [mre/tenant-frontend:latest internal] load build context
#7 transferring context: 4.62kB 0.0s done
#7 DONE 0.1s

#8 [mre/tenant-frontend:latest  1/16] FROM docker.io/library/node:16-alpine@sha256:296dd8ebd5b68706cc35d85e3c5b0103b28d2c0e8fde7e2feff68e4072636d6a
#8 resolve docker.io/library/node:16-alpine@sha256:296dd8ebd5b68706cc35d85e3c5b0103b28d2c0e8fde7e2feff68e4072636d6a 0.0s done
#8 DONE 0.1s

#9 [mre/landlord-frontend:latest internal] load build context
#9 transferring context: 16.60kB 0.0s done
#9 DONE 0.1s

#10 [mre/tenant-frontend:latest 14/16] COPY webapps/tenant/package.json webapps/tenant
#10 CACHED

#11 [mre/tenant-frontend:latest 12/16] COPY webapps/tenant/i18n.js webapps/tenant
#11 CACHED

#12 [mre/tenant-frontend:latest  4/16] COPY package.json .
#12 CACHED

#13 [mre/tenant-frontend:latest  5/16] COPY yarn.lock .
#13 CACHED

#14 [mre/tenant-frontend:latest  9/16] COPY webapps/tenant/locales webapps/tenant/locales
#14 CACHED

#15 [mre/tenant-frontend:latest 11/16] COPY webapps/tenant/.eslintrc.json webapps/tenant
#15 CACHED

#16 [mre/tenant-frontend:latest 13/16] COPY webapps/tenant/next.config.js webapps/tenant
#16 CACHED

#17 [mre/tenant-frontend:latest  6/16] COPY .eslintrc.json .
#17 CACHED

#18 [mre/tenant-frontend:latest  7/16] COPY webapps/commonui webapps/commonui
#18 CACHED

#19 [mre/tenant-frontend:latest 10/16] COPY webapps/tenant/src webapps/tenant/src
#19 CACHED

#20 [mre/tenant-frontend:latest  8/16] COPY webapps/tenant/public webapps/tenant/public
#20 CACHED

#21 [mre/tenant-frontend:latest 15/16] COPY webapps/tenant/LICENSE webapps/tenant
#21 CACHED

#22 [mre/landlord-frontend:latest  6/16] COPY .eslintrc.json .
#22 CACHED

#23 [mre/landlord-frontend:latest 14/16] COPY webapps/landlord/package.json webapps/landlord
#23 CACHED

#24 [mre/landlord-frontend:latest  9/16] COPY webapps/landlord/locales webapps/landlord/locales
#24 CACHED

#25 [mre/landlord-frontend:latest  4/16] COPY package.json .
#25 CACHED

#26 [mre/landlord-frontend:latest  5/16] COPY yarn.lock .
#26 CACHED

#27 [mre/landlord-frontend:latest 13/16] COPY webapps/landlord/next.config.js webapps/landlord
#27 CACHED

#28 [mre/landlord-frontend:latest  2/16] RUN apk --no-cache add build-base python3
#28 CACHED

#29 [mre/landlord-frontend:latest 12/16] COPY webapps/landlord/i18n.js webapps/landlord
#29 CACHED

#30 [mre/landlord-frontend:latest  8/16] COPY webapps/landlord/public webapps/landlord/public
#30 CACHED

#31 [mre/landlord-frontend:latest  7/16] COPY webapps/commonui webapps/commonui
#31 CACHED

#32 [mre/landlord-frontend:latest  3/16] WORKDIR /usr/app
#32 CACHED

#33 [mre/landlord-frontend:latest 10/16] COPY webapps/landlord/src webapps/landlord/src
#33 CACHED

#34 [mre/landlord-frontend:latest 11/16] COPY webapps/landlord/.eslintrc.json webapps/landlord
#34 CACHED

#35 [mre/landlord-frontend:latest 15/16] COPY webapps/landlord/LICENSE webapps/landlord
#35 CACHED

#36 [mre/landlord-frontend:latest 16/16] RUN yarn workspace @microrealestate/landlord install --frozen-lockfile &&     yarn cache clean &&     yarn workspace @microrealestate/landlord run build
#36 1.377 yarn workspace v1.22.19
#36 2.028 yarn install v1.22.19
#36 2.454 [1/4] Resolving packages...
#36 ...

#37 [mre/tenant-frontend:latest 16/16] RUN yarn workspace @microrealestate/tenant install --frozen-lockfile &&     yarn cache clean &&     yarn workspace @microrealestate/tenant run build
#0 1.369 yarn workspace v1.22.19
#0 2.022 yarn install v1.22.19
#0 2.434 [1/4] Resolving packages...
#37 20.29 [2/4] Fetching packages...
#37 ...

#36 [mre/landlord-frontend:latest 16/16] RUN yarn workspace @microrealestate/landlord install --frozen-lockfile &&     yarn cache clean &&     yarn workspace @microrealestate/landlord run build
#36 20.81 [2/4] Fetching packages...
#36 ...

#37 [mre/tenant-frontend:latest 16/16] RUN yarn workspace @microrealestate/tenant install --frozen-lockfile &&     yarn cache clean &&     yarn workspace @microrealestate/tenant run build
#37 70.44 info There appears to be trouble with your network connection. Retrying...
#37 ...

#36 [mre/landlord-frontend:latest 16/16] RUN yarn workspace @microrealestate/landlord install --frozen-lockfile &&     yarn cache clean &&     yarn workspace @microrealestate/landlord run build
#36 70.50 info There appears to be trouble with your network connection. Retrying...

**Comment by robbinmoreka** [comment]
also the network connection is fine

**Comment by camelaissani** [comment]
It will be tackled in #85
