### ISSUE TITLE
 Invoice for additional costs

### ISSUE THREAD

**Issue by Syndlex** [microrealestate/microrealestate#93]
Are there any plans to add a functionality for invoices for additional costs?

The Project is very interesting but this would be the last think i would need.

I would like to contribute here, when the is a plan how the best and simples implementation of this would be.

Thank you for the work. :)

**Comment by camelaissani** [comment]
Hi @Syndlex 
Did you see that you can add additional cost in the tenant lease form or/and in the rent payment form?
<img src="https://user-images.githubusercontent.com/7079471/211223100-888dac45-1e6d-4389-9774-4b2b02e4122c.png" width="400" />

<img src="https://user-images.githubusercontent.com/7079471/211223106-d322a94f-32b8-4c22-8945-013c6e635d4b.png" width="400" />

**Comment by Syndlex** [comment]
@camelaissani 
Hey, yes this is something I had in mind.

The use-case i thought about is, having a Property with multiple Tenants and the additional costs are divided between the Tenants.

Tenants pay these cost monthly. But it can happen that they have to pay more at the end of the year when something like electricity cost more than thought.

I would like to send this yearly invoice separately.
I don't know if this is just a German thing. :man_shrugging:
