### ISSUE TITLE
Change email agent to generic SMTP

### ISSUE THREAD

**Issue by LAX18** [microrealestate/microrealestate#94]
First off, fantastic work on this. I did some digging into your mailer code and am curious if you could provide an option to use a personal email server with SMTP rather than relying on your current email solution. Looking to remove overhead for my small business.

If it's something trivial, I could implement it but would need some guidance and/or better docs on your mailer code.

**Comment by camelaissani** [comment]
Thank you 😉
Did you see this doc https://github.com/microrealestate/microrealestate/blob/master/services/emailer/README.md

**Comment by LAX18** [comment]
I did not! I'll take a look. Thanks!

**Comment by camelaissani** [comment]
Your issue is still interesting. I think nodemailer might be used in the emailer service and then allow to use a personal email server.

**Comment by camelaissani** [comment]
@LAX18 finally the support to generic SMTP has been added by @zeronounours see #139
